#pragma once

#include "NativeGameplayTags.h"

namespace SekiroGameplayTags
{
	//Input Tags
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MeleeAttack_Katana)
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable)
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld)
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipKatana)
	
	// Player Tags
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerTag_Weapon_Katana)
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerTag_Ability_Equip_Katana)
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(PlayerTag_Ability_Attack_Katana)

	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Eqip_Katana)
	
	SEKIROPROJ_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Katana)
}